package dev.sirius.cloud.wrapper.process;

import dev.sirius.cloud.api.group.ServiceGroup;
import dev.sirius.cloud.api.logging.CloudLogger;
import dev.sirius.cloud.api.service.ServiceInfo;
import dev.sirius.cloud.wrapper.util.FileUtil;
import org.yaml.snakeyaml.DumperOptions;
import org.yaml.snakeyaml.Yaml;

import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;

/**
 * Writes the configuration a service needs before it is started.
 *
 * <p>Servers and proxies share almost nothing here: a proxy has no
 * {@code server.properties} and no EULA, a server has no listener config, and
 * the two ends of Velocity's modern forwarding are set up from opposite sides.
 */
public final class ServiceConfigurator {

    private static final CloudLogger LOGGER = CloudLogger.of("Configurator");

    private ServiceConfigurator() {
    }

    // ---------------------------------------------------------------- server

    public static void writeEula(Path directory) throws IOException {
        FileUtil.writeString(directory.resolve("eula.txt"),
                "# Generated by SiriusCloud. By running this service you accept\n"
                        + "# the Minecraft EULA: https://aka.ms/MinecraftEULA\n"
                        + "eula=true\n");
    }

    /**
     * Writes the port the node allocated, preserving anything the template set.
     */
    public static void writeServerProperties(Path directory, ServiceInfo info, ServiceGroup group,
                                             String bindAddress) throws IOException {
        Path path = directory.resolve("server.properties");
        Properties properties = new Properties();

        if (Files.isRegularFile(path)) {
            try (Reader reader = Files.newBufferedReader(path, StandardCharsets.UTF_8)) {
                properties.load(reader);
            }
        }

        // The node owns these. Anything else is the template's business.
        properties.setProperty("server-port", String.valueOf(info.port()));
        properties.setProperty("server-ip", bindAddress == null ? "" : bindAddress);
        properties.setProperty("max-players", String.valueOf(group.maxPlayers()));
        properties.setProperty("motd", info.name());

        // The proxy authenticates players; the backend must not try to as well.
        // Safe only because modern forwarding is configured below - without it
        // this line alone would let anyone reach the backend port as anyone.
        properties.setProperty("online-mode", "false");

        properties.putIfAbsent("enable-rcon", "false");
        properties.putIfAbsent("enable-query", "false");
        properties.putIfAbsent("spawn-protection", "0");

        try (Writer writer = Files.newBufferedWriter(path, StandardCharsets.UTF_8)) {
            properties.store(writer, "Managed by SiriusCloud - server-port is assigned by the node");
        }
    }

    /**
     * Turns on Velocity modern forwarding in {@code config/paper-global.yml}.
     *
     * <p>Merged into whatever is already there rather than overwritten: the
     * file carries a lot of unrelated tuning that a template may legitimately
     * set, and replacing it wholesale would silently discard all of it. Paper
     * fills in any keys neither we nor the template wrote.
     */
    @SuppressWarnings("unchecked")
    public static void enableVelocityForwarding(Path directory, String forwardingSecret) throws IOException {
        if (forwardingSecret == null || forwardingSecret.isBlank()) {
            LOGGER.warn("No forwarding secret; this server will not accept proxied players.");
            return;
        }

        Path path = directory.resolve("config").resolve("paper-global.yml");
        Files.createDirectories(path.getParent());

        DumperOptions options = new DumperOptions();
        options.setDefaultFlowStyle(DumperOptions.FlowStyle.BLOCK);
        options.setPrettyFlow(true);
        Yaml yaml = new Yaml(options);

        Map<String, Object> root = new LinkedHashMap<>();
        if (Files.isRegularFile(path)) {
            try (Reader reader = Files.newBufferedReader(path, StandardCharsets.UTF_8)) {
                Map<String, Object> loaded = yaml.load(reader);
                if (loaded != null) {
                    root = new LinkedHashMap<>(loaded);
                }
            } catch (Exception exception) {
                LOGGER.warn("Could not read paper-global.yml ({}), writing a fresh one",
                        exception.getMessage());
            }
        }

        Map<String, Object> proxies = (Map<String, Object>) root.computeIfAbsent(
                "proxies", key -> new LinkedHashMap<String, Object>());
        Map<String, Object> velocity = (Map<String, Object>) proxies.computeIfAbsent(
                "velocity", key -> new LinkedHashMap<String, Object>());

        velocity.put("enabled", true);
        velocity.put("online-mode", true);
        velocity.put("secret", forwardingSecret);

        try (Writer writer = Files.newBufferedWriter(path, StandardCharsets.UTF_8)) {
            yaml.dump(root, writer);
        }
    }

    /** Forces {@code bind} in an existing velocity.toml to the allocated port. */
    private static void rewriteBindPort(Path path, int port) throws IOException {
        List<String> lines = Files.readAllLines(path, StandardCharsets.UTF_8);
        String replacement = "bind = \"0.0.0.0:" + port + "\"";

        boolean replaced = false;
        for (int i = 0; i < lines.size(); i++) {
            if (lines.get(i).stripLeading().startsWith("bind")) {
                lines.set(i, replacement);
                replaced = true;
                break;
            }
        }
        if (!replaced) {
            lines.add(0, replacement);
        }

        Files.write(path, lines, StandardCharsets.UTF_8);
    }

    // ----------------------------------------------------------------- proxy

    /**
     * Writes {@code velocity.toml} and the forwarding secret.
     *
     * <p>No {@code [servers]} entries: the proxy learns about backends from the
     * node at runtime, which is the entire reason for the cloud. A listed
     * server here would be one the cloud does not manage.
     */
    public static void writeVelocityConfig(Path directory, ServiceInfo info, ServiceGroup group,
                                           String forwardingSecret) throws IOException {
        FileUtil.writeString(directory.resolve("forwarding.secret"),
                forwardingSecret == null ? "" : forwardingSecret);

        Path path = directory.resolve("velocity.toml");
        if (Files.isRegularFile(path)) {
            // A template supplied one deliberately, so keep every choice in it
            // except the listen port: that one is the node's to assign. A
            // template hardcoding it would collide with every other proxy from
            // the same template, and leave the node advertising an address
            // nothing is listening on.
            rewriteBindPort(path, info.port());
            LOGGER.debug("Kept the template's velocity.toml for {}, bind set to {}",
                    info.name(), info.port());
            return;
        }

        FileUtil.writeString(path, """
                # Generated by SiriusCloud. Backends are registered at runtime
                # by the cloud plugin, so [servers] is intentionally empty.
                config-version = "2.7"

                bind = "0.0.0.0:%d"
                motd = "%s"
                show-max-players = %d
                online-mode = true
                force-key-authentication = true
                prevent-client-proxy-connections = false

                player-info-forwarding-mode = "modern"
                forwarding-secret-file = "forwarding.secret"

                announce-forge = false
                kick-existing-players = false
                ping-passthrough = "DISABLED"
                enable-player-address-logging = true

                [servers]
                try = []

                [forced-hosts]

                [advanced]
                compression-threshold = 256
                compression-level = -1
                login-ratelimit = 3000
                connection-timeout = 5000
                read-timeout = 30000
                haproxy-protocol = false
                tcp-fast-open = false
                bungee-plugin-message-channel = true
                show-ping-requests = false
                failed-server-kick-reason = "Internal server connection error"
                announce-proxy-commands = true
                log-command-executions = false
                log-player-connections = true

                [query]
                enabled = false
                port = %d
                map = "Velocity"
                show-plugins = false
                """.formatted(info.port(), info.name(), group.maxPlayers(), info.port()));
    }
}
